### ISSUE TITLE
Fix diffusion_food and diffusion_metabolite functions

### ISSUE THREAD

**Issue by swom** [swom/project1_vG_W_2016#11]
These 2 function do not work as intended, check and fix the tests. 

These two functions are too big and are the same thing with different arguments, try to find a way to break them into smaller functions that can work on both, so that you have a more elegant unified funtion

**Comment by swom** [comment]
It is difficult to shorten the code I think without using template functions, maybe I should wait and learn a bit more before trying to do this. Sadly...

**Comment by swom** [comment]
@richelbilderbeek if you are looking through the code:
For some reason the function `diffusion()` really messes things up when a second individual is present in the simulation.  I am not really sure why, since the logic concerning individuals and the environment, should be separated. I think the problem lies in the function `redistribute_substances()`, could you perhaps give a look?
The test for this is at line 723 of `simulation.cpp`

**Comment by richelbilderbeek** [comment]
Taking a look :+1:

**Comment by richelbilderbeek** [comment]
Hmmm, I find this code a bit smelly, and I will suggest changes after this.

```c++
void calc_diffusion_food(environment& e) noexcept
{
  for(auto& cell : e.get_grid())
    {
      auto v_food_deltas = get_neighbors_food_deltas(cell, e);
      auto exiting_food = calc_exiting_food(cell, v_food_deltas, e.get_diff_coeff());
      cell.increment_food_change(- exiting_food);

      for(unsigned int i = 0; i != cell.get_v_neighbors().size(); i++)
        {
          auto recieved_food = exiting_food *
              ( cell.get_tot_food_delta() > 0 ? v_food_deltas[i]/cell.get_tot_food_delta() : 0);
          e.get_cell(cell.get_v_neighbors()[i]).increment_food_change(recieved_food);
        }
    }
}
```

Problem is that you use a ranged for loop (i.e. working on elements of the grid) while working on the elements of the grid. I suggest to separate the current from the next grid.

The function signature will be:

```
environment do_diffusion(const environment& e) noexcept
{
  
}
```

Important is that the original environment is `const`.

Also, in this way, you can -yes, here I go!- better test the function: simply create a 3x3 grid with one food patch and let the diffusion take place. Easy peasy.

I hope this helps :+1: Time to :zzz:

**Comment by swom** [comment]
Hello @richelbilderbeek. Thanks for the tip. I will see what I can do for it. 
The thing is that it seems diffusion works correctly also in this case. It stops working only when individuals on the grid(which the grid should not know about start reproducing. I have no clue why this is so, and already checked that it  has nothing to do with the division function. It seems that after individuals reproduce the total amount of food in the system is increased somehow, even though division does not call any element of environment and environment does not call any element of individual and population. 
Anyway I will try to just reimplement things as you suggested, and maybe that will take care of the bug. Thnks again

**Comment by swom** [comment]
Hello @richelbilderbeek, I have changed the function so it gives back a new grid (std::vector<env_grid_cell>) and it takes a constant environment as a variable. But unfortunately, the same bug keeps happening. Once individuals reproduce, and diffusion is called, for some reason the food increases in the simulation. If you have time maybe have a look.

**Comment by swom** [comment]
@richelbilderbeek. Found it, was a mistake in the logic of the function `void env_grid_cell::increment_food()`

**Comment by richelbilderbeek** [comment]
@swom: well spotted! I think this is related to something I wanted to add in the review (#55), but did not have time for. Let's do now :+1:

I think lines such as these are risky, (from [here](https://github.com/swom/project1_vG_W_2016/blob/develop/env_grid_cell.h#L30)):

```c++
void increment_food(double f) noexcept {m_food + f > -0.0000001 ? m_food += f : m_food = 0;}
```

I see the intention: food should only go up. But instead of preventing this, a band-aid is applied that 'fixes' the problem in-place. I feel the cure is worse than the problem: the tests for this behavior must have looked smelly.

I would suggest to ruthlessly abort the program when something weird happens:

```c++
/// Increases the amount of food.
/// f must be zero or positive.
void increase_food(double f) noexcept {
  assert(f >= 0.0);
  assert(m_food >= 0.0); //Optional, as due to rounding errors, things may go below zero
  m_food += f;
}
```

This makes the code do what a programmer expects :+1:

In my eyes, this version would be even superior:

```c++
/// Change the amount of food.
void change_food(double f) noexcept {
  m_food += f;
}
```

I think so, because in *reality* food may both increase and decrease. I understand that in your *implementation* food should only increase, but reality is the basis behind our ideas.

Again, as always, feel free to ignore :sunglasses: :+1:
