### ISSUE TITLE
develop not working/compiling on peregrine cluster

### ISSUE THREAD

**Issue by swom** [swom/project1_vG_W_2016#128]
@richelbilderbeek perhaps you could solve this quite easily.
I have tried to run some simulations on the cluster and for some reasons now it seems that the make command does not work. 
Using any of the .sh scripts that start with run_mulitple*, you can see for yourself
Checking the output of make, I see multiple errors of the type ":c : Command not found".
Could you perhaps try and see if you can make it work/it already works for you? Do you know what might be causing this issue?

**Comment by swom** [comment]
it seems this is due to the fact that the makefile does not specify the compiler correctly. I checked on the Makefile.release and indeed in the fields:
```
CC =
CXX =
```
nothing is specified. Might it be that something is not allowing qmake to knwo with which compiler it needs to operate?

**Comment by swom** [comment]
It seems that if I specify the compiler in the Makefile.release as suggested [here](https://stackoverflow.com/questions/5256663/make-c-command-not-found) then make command works and the program compiles. How come that qmake is not able to specify the compiler on its own?

**Comment by swom** [comment]
No I correct myself, it STARTS compiling (at least) and then gives an error due to the glm library.

**Comment by swom** [comment]
@HHildenbrandt would you perhaps now what might cause this issue? I am still not using the cmake branch, but instead the qmake and make command in develop.

**Comment by swom** [comment]
I have the module Qt5 loaded  as well as GCC/9.3.0

**Comment by richelbilderbeek** [comment]
@swom I read your Issue now. ~~Want me to try now?~~ Working on it now.

**Comment by swom** [comment]
Please do,
if you have time,

Thanks

**Comment by richelbilderbeek** [comment]
This works, call `qmake` as such on Peregrine:

```
module load Qt5; export CC=g++; export CXX=g++; qmake simulation_logic_only.pro
```

Then simply call `make`.

Here is part of my output:
```
p230198@peregrine:project1_vG_W_2016 module load Qt5; export CC=g++; export CXX=g++; qmake simulation_logic_only.pro
p230198@peregrine:project1_vG_W_2016 make
make -f Makefile.Release
make[1]: Entering directory `/home/p230198/GitHubs/project1_vG_W_2016'
g++ -c -m64 -pipe -std=c++17 -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -pg -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC -DLOGIC_ONLY -DNDEBUG -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -Ilibs -I/apps/haswell/software/Qt5/5.14.1-GCCcore-9.3.0/include -I/apps/haswell/software/Qt5/5.14.1-GCCcore-9.3.0/include/QtGui -I/apps/haswell/software/Qt5/5.14.1-GCCcore-9.3.0/include/QtCore -Irelease -I/apps/haswell/software/Qt5/5.14.1-GCCcore-9.3.0/mkspecs/linux-g++-64 -o release/grid_view.o grid_view.cpp
g++ -c -m64 -pipe -std=c++17 -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -pg -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC -DLOGIC_ONLY -DNDEBUG -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -Ilibs -I/apps/haswell/software/Qt5/5.14.1-GCCcore-9.3.0/include -I/apps/haswell/software/Qt5/5.14.1-GCCcore-9.3.0/include/QtGui -I/apps/haswell/software/Qt5/5.14.1-GCCcore-9.3.0/include/QtCore -Irelease -I/apps/haswell/software/Qt5/5.14.1-GCCcore-9.3.0/mkspecs/linux-g++-64 -o release/grn.o grn.cpp
...

p230198@peregrine:project1_vG_W_2016 ./simulation_logic_only 
[Does something, no patience to wait for output]
```

Done!

**Comment by richelbilderbeek** [comment]
If this does not solve the problem, let me know. Else you can close the Issue :sunglasses: :+1:

**Comment by swom** [comment]
It works  👍. Why is it now necessary to specify the compilers, while this was not the case before? Also what is the exact function of the export command?
Anyway thanks!

**Comment by richelbilderbeek** [comment]
> Why is it now necessary to specify the compilers, while this was not the case before? 

Because you/we wanted to support multiple compilers on Travis: Travis now determines which compiler to use from the environmental variables

> Also what is the exact function of the export command?

It set the environmental variables :grin::+1:

**Comment by HHildenbrandt** [comment]
Cool - qmake on peregrine ;)
Thanks Richel
