### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by swom** [swom/project1_vG_W_2016#67]
@richelbilderbeek how can I profile my program? I guess Travis can take care of it right?

**Comment by richelbilderbeek** [comment]
Definitely Travis can do that! See an example [here](https://github.com/richelbilderbeek/the_richel_setup#profile)

**Comment by swom** [comment]
To be clear: do I just have to add a` head gprof.log n -1000  command` to my Travis.yml file?

**Comment by swom** [comment]
Sry, I had a look at the .travis.yml from the richel setup repository. I tried to run the same commands you wrote in the repository but it does not seem to work. Travis complains about the fact that the gmon.out file is not found. I see from online tutorials that I should compile using the `-pg` but I do not see it in your travis file

**Comment by richelbilderbeek** [comment]
@swom added! It's on the `develop` branch. Enjoy :+1:

**Comment by richelbilderbeek** [comment]
@swom note that the conclusions of the profile are preliminary! 

Things to change/check:

 * Let the profile run for a longer time. I usually strive for at least 1 minute, max 10 minutes
 * Use a representative setting for a profile run, with -for example, a regular population size. Increasing population sizes may have more than just a linear effect on run-time. Running a simulation for more generations, *usually* has a linear effect

I tend to add the option to do a profile run with `./simulation --profile`.

Again, enjoy :+1:

**Comment by swom** [comment]
Thanks Richel. I will think of how to make use of it the best. I still struggle to interpret the call graphs, since it seems that some sfml classes are called on Travis, where they should not be evoked, but I will struggle with it a bit more. I think I will close the issue now.
