### ISSUE TITLE
QT has problems integrating libraries from hanno to use hilbert_tree collision management

### ISSUE THREAD

**Issue by swom** [swom/project1_vG_W_2016#78]
@richelbilderbeek can I ask you a favour?
I have been struggling the last few days to integrate the libraries that Hanno put at my disposal to improve the speed of my collision_managment for my simulation. It is pretty important for me to get them to work, as they would make my life significantly easier in running more simulations.
The problem is that this libraries were written in visual studio and as I feared they do not seem to compile with my actual setting in QT.
I would really like to keep the setting as it is and not have to shift to Visual Studio, especially because I am not sure Travis could work with a Visual Studio project.
The situation for now is as follow:
- 1 I have my QT creator project, building with the mingw73_64 and using the corresonding sfml library
- 2 I include Hanno's libraries by using `INCLUDEPATH +=` in the .pro file. They are all header-only. It seems the project can find them and include them succesfully.
- 3 If I try to build though multiple errors pop up, I am not entirely sure what they precisely mean, but it seems to me that most of them do not understand the syntax of these files
- 4 Even if I turn off all the error flags and warning flags in the  .pro file errors still pop up
- 5 Even though Hanno tried to compile these files with MinGW and succeded, I am pretty positive this errors are caused by some incompatibility between the code and the compiler/QT creator setup
- 6 I therefore tried to create a kit where the build is done by using the Visual Studio tool_chain, but with little success. From my understanding what I need is a MSVC compiler instead of the Min_GW. Unfortunately the QT creator I have installed does not have this compiler, it can still detect the one I have installed with Visual Studio but it seems I am missing some other pieces to create a functioning kit to build the project with it. I am not what is it that I am doing wrong but for now I don't think I can solve it.
- 7 I therefore resigned myself to reinstall Qt creator this time making sure it comes already with the MSVC kit included and I will try to see if the program will run with it.

So given that this is the situation, I would like to ask you a couple of questions since you have much more experience than me using Qt creator:
- [ ] 1)If I change compiler do I need to change something in the `travis.yml` file?
- [ ] 2) Is it possible to create a functioning kit by using Visual studio toolchain? I know you prbably do not know since you do not use Visual Studio
- [ ] 3) Might it be that the failure to compile is due to the error flags in my .pro file?
- [ ] 4) Would you happen to know if Travis an take on Visual Studio projects?

I hope you will find the time to answer some of this questions,
Thanks

**Comment by richelbilderbeek** [comment]
Will answer and work on this on Saturday :+1:

**Comment by richelbilderbeek** [comment]
Hi Stefano,

I got it to work locally! Here are the answers to your questions:


> 1)If I change compiler do I need to change something in the travis.yml file?

Yes, for example, for clang:

```
QMAKE_CXX = clang
```

> 2) Is it possible to create a functioning kit by using Visual studio toolchain? 
> I know you prbably do not know since you do not use Visual Studio

I predict yes, but -indeed- I don't know how.

> 3) Might it be that the failure to compile is due to the error flags in my .pro file?

Yes, you forgot to link to openmp (whatever that is). So I added:

```
QMAKE_CXXFLAGS += -fopenmp
LIBS += -fopenmp
```

I also had to tolerate warnings, as it does not compile cleanly under GCC 9.

```
# Commented out :-(
# QMAKE_CXXFLAGS += -Werror
```

> 4) Would you happen to know if Travis an take on Visual Studio projects?

I don't know. I guess AppVeyor (Travis, but then for Windows) is the way
that is likelier to succeed.

Cheers, Richel

**Comment by swom** [comment]
Thanks @richelbilderbeek l

**Comment by richelbilderbeek** [comment]
Happy to help!

**Comment by richelbilderbeek** [comment]
Can this Issue be closed?

**Comment by swom** [comment]
👍
