### ISSUE TITLE
Not running on peregrine. Why?

### ISSUE THREAD

**Issue by swom** [swom/project1_vG_W_2016#98]
@richelbilderbeek 
I am trying to finally give the program a first few runs on the cluster, but it seems it is not able to compile on peregrine. When you have time could you perhaps see what is wrong now?
The log messages report some undefined references linked to some multithreading options in Hanno's library, but I remember we solved this problem last time already. Let me know what you think.

**Comment by richelbilderbeek** [comment]
I predict you need to load some modules. Sure, let's meet at my place and fix these :+1:

**Comment by swom** [comment]
Hello Richel,
As you might remember at this moment I am in Paris. We can meet over discord if you-d like, or google meets or teamviewer. When would you be available?

**Comment by richelbilderbeek** [comment]
Ah, my bad! 

Would Monday/tomorrow 16:00 to max 17:00 work for you?

**Comment by swom** [comment]
Tomorrow I have a meeting at 15.00 that could go longer than 16.00, but hopefully not longer than 17.00.
Maybe perhaps we can try tomorrow but keeping in mind we might have to reschedule. And since I do not wanna lose too much of your time, we could instead fix it for Tuesday?  Let me know.

**Comment by richelbilderbeek** [comment]
Sounds great to me! I'll be around on Discord from 16:00-17:00, Tuesday 16:00-17:00 would also work if needed :+1:

**Comment by swom** [comment]
Great, thanks a lot @richelbilderbeek

**Comment by richelbilderbeek** [comment]
To sum up: the program did not compile, as it was compiled by two jobs at the same time.

I suggest to close this one :+1:
